### ISSUE TITLE
Great job! Any plan to make a Rust version?

### ISSUE THREAD

**Issue by to-always-be-a-learner** [yhzhang0128/egos-2000#2]
As a modern systems languages, Rust is very expressive while retaining the high performance. It's a good candidate to write OS which may requires few lines of code, hence being more readable and understandable, hopefully.

**Comment by yhzhang0128** [comment]
Thanks for your suggestion. I have been thinking about this and below are my thoughts. I'd be happy to hear your opinions.

The goal of Rust, as well as other high-level languages, is to **hide** low-level details for security and correctness. For example, the linear type in Rust aims at hiding memory management. 

The goal of OS education, in contrast, is to **expose** low-level details. For example, the connection between C and the CPU ISA is very close and natural, so that it is easier for students to connect their OS course with architecture course. 

I guess I still hope students could focus on the low-level connection between OS and architecture. I think after the OS course, a further course on software engineering could focus on security and correctness, including programming language support.

**Comment by strlcat** [comment]
Why is anyone so obsessed with Rust? I agree with @yhzhang0128 , the goal is to _learn_ low level tech there, not hide it.

**Comment by yhzhang0128** [comment]
> Why is anyone so obsessed with Rust? I agree with @yhzhang0128 , the goal is to _learn_ low level tech there, not hide it.

Thanks for the comment. To be fair, Rust is a very good language. In my other work, I use Rust and I found it to be very productive.
